Display mode refactor
LiveTL/LiveTL pull request #300
Opened 2021-08-12 22:13 UTC by KentoNishi

Replaced `isStandalone` and `paramsEmbedded` usages with a `displayMode` store. This would be helpful for conditionals in the upcoming holodex implementation, where we can just add a new `DisplayMode.HOLODEX` enum

2021-08-12 22:26 UTC, r2dev2 approved these changes

2021-08-12 22:45 UTC, r2dev2 requested changes

2021-08-12 22:45 UTC, r2dev2 commented on src/components/Watch.svelte
> +  import { isResizing } from '../js/store.js';
Put above the ``document.title`` line or use ``svelte:window`` to set the title.

2021-08-12 22:45 UTC, r2dev2 commented on src/components/Watch.svelte
> +      [$displayMode === DisplayMode.FULLPAGE ? vidElem : null, $videoSide == VideoSide.TOP ? 'height' : 'width', videoPanelSize]
This is kinda cluttered. You could move the ``videoSide`` ternary to a reactive statement since you use the same expression on line ``113``.

2021-08-12 22:45 UTC, r2dev2 commented on src/components/Wrapper.svelte
> +    display: {$isResizing
Can you refactor this to use ``class:d-none`` and ``class:d-grid``.

2021-08-12 22:45 UTC, r2dev2 commented on src/components/Watch.svelte
> +  import { isResizing } from '../js/store.js';
nvm you fixed this

2021-08-12 23:40 UTC, r2dev2 requested changes

2021-08-12 23:40 UTC, r2dev2 commented on src/components/Watch.svelte
>              : ''}"
Please extract this into a reactive statement.

2021-08-12 23:40 UTC, r2dev2 commented on src/components/Watch.svelte
> +        {isRightSide ? 'reversed' : ''}"
Please use ``class:`` with this. If you don't want to set two class directives, you can just set a default css value and set a class that overrides the default one.

2021-08-12 23:40 UTC, r2dev2 commented on src/components/Watch.svelte
> +          class="flex {isChatVertical
See line 119 comment

2021-08-12 23:40 UTC, r2dev2 commented on src/components/Watch.svelte
>                : 'height'}: 10px;
Just use one ``isChatVertical`` ternary expression to set both ``width|height`` and ``min-width|min-height``.

2021-08-13 06:33 UTC, KentoNishi commented
found my own issues, don't accept this yet

2021-08-13 06:47 UTC, KentoNishi commented
@ChrRubin @r2dev2 fixed, plz review

2021-08-13 06:47 UTC, r2dev2 approved these changes

2021-08-13 07:46 UTC, ChrRubin requested changes

2021-08-13 07:46 UTC, ChrRubin commented on src/components/settings/UISettings.svelte
>        options={Object.keys(VideoSide)}
Probably better to change to only show on `FULLPAGE`, video side doesn't do anything for embed mode anyway.

2021-08-13 07:46 UTC, ChrRubin commented on src/components/settings/UISettings.svelte
>  {/if}
Same as above, should only show on `FULLPAGE`.

2021-08-13 07:46 UTC, ChrRubin commented on src/components/settings/UISettings.svelte
>  {#if $showCaption}
Extra caption settings will always be shown if captions are enabled regardless of display mode.

2021-08-13 07:46 UTC, ChrRubin commented on src/components/Popout.svelte
>    import { TextDirection, paramsVideoTitle, paramsEmbedded, isAndroid } from '../js/constants.js';
Unused import `paramsEmbedded`

2021-08-13 07:46 UTC, ChrRubin commented on src/components/Watch.svelte
> +    (isTopSide ? 'height' : `width`) + `: ${$videoPanelSize}%; ` +
`width` is in backticks instead of single quotes

2021-08-13 20:24 UTC, r2dev2 requested changes

2021-08-13 20:24 UTC, r2dev2 commented on src/js/store.js
> +export const displayMode = writable(paramsEmbedded ? DisplayMode.EMBEDDED : DisplayMode.FULLPAGE);
This seems like it should be a constant value though. You only set it once before the app is mounted. Maybe try moving this to constants and getting the page type by setting a ``window`` value before the app mounts or by checking the url.

2021-08-13 20:40 UTC, r2dev2 commented on src/js/store.js
> +export const displayMode = writable(paramsEmbedded ? DisplayMode.EMBEDDED : DisplayMode.FULLPAGE);
Nvm, this is better.

2021-08-13 20:40 UTC, r2dev2 approved these changes

2021-08-13 20:41 UTC, merged