v6.8
LiveTL/LiveTL pull request #329
Opened 2021-08-26 23:10 UTC by KentoNishi

## No more unavailable videos!

Previously, YouTube and/or streamers blocked third-party sites from opening some streams. This prevented users from watching membership streams and certain channels in the full-page LiveTL viewer. We've come up with a workaround that forces videos to play anyway! No longer do you need to resort to LiveTL's embedded mode to watch restricted streams.

2021-08-27 07:06 UTC, ChrRubin commented
Chat doesn't seem to work well with VODs that were normally unavailable. Either messages will just fail to load completely or it'll stop showing chunks after finishing the current chunk. Tested with: https://www.youtube.com/watch?v=6WFU2wzPKfA

Also doesn't work for members-only VODs, it shows a slightly different "video is not available" screen:
![image](https://user-images.githubusercontent.com/20059164/131087739-d24b9d09-bc9c-487a-8c65-1b488d3e4a86.png)

2021-08-28 04:06 UTC, KentoNishi commented
@ChrRubin 
![image](https://user-images.githubusercontent.com/38841491/131205617-cae7910f-6fa7-4e65-85ed-7abecec89b91.png)

it works totally fine for me. this uses a new content script so i think u might have to fully reinstall the dev build for it to take effect. can u try that?

2021-08-28 04:07 UTC, KentoNishi commented
also i can't test membership streams cuz im a peasant :(

2021-08-28 09:23 UTC, ChrRubin commented
Hmm, chat seems to be inconsistent on whether or not its working with this workaround. Every few refreshes of the page the chat will just stop working, even with VODs that are normally available. I'll see if I can find a pattern on what's causing it to break. 

And yeah members-only's won't work, at least from what I've tried with Ina's members-only's.

2021-08-28 09:26 UTC, ChrRubin commented
Lol even non-HC chat breaks inconsistently, weird...

2021-08-31 09:11 UTC, ChrRubin commented
Yeah the workaround seems fine most of the time, and only occasionally chat will break for whatever reason.

If possible I'd like it to use the normal embed by default and only use the workaround for unavailable videos, but that depends on whether the player API exposes something that lets us know that the video is unavailable.

2021-09-13 05:04 UTC, r2dev2 requested changes
Just some `console.logs` to remove, we also need to wait for me to finish keyboard shortcuts.

2021-09-13 05:04 UTC, r2dev2 commented on src/components/options/Dropdown.svelte
> +  $: console.log(items);
remove

2021-09-13 05:04 UTC, r2dev2 commented on src/js/content_scripts/injector.js
> +  console.log(autoLaunchMode.get());
remove

2021-09-13 05:04 UTC, r2dev2 commented on src/js/utils.js
> +function capitalize(s) {
Can you export this as well?

2021-09-22 04:11 UTC, ChrRubin commented
Can we get #347 checked and merged for 6.8?

2021-09-22 04:23 UTC, KentoNishi commented
> Can we get #347 checked and merged for 6.8? 

Sure yea I'll do it in a bit

2021-09-22 05:31 UTC, r2dev2 reviewed
I made the TLTalk ad more concise and apparent and this pr looks good. Waiting for #347 to be merged (I approved that one, @KentoNishi pls review and merge).

2021-09-22 06:39 UTC, r2dev2 approved these changes

2021-09-22 07:17 UTC, ChrRubin approved these changes

2021-09-22 07:19 UTC, merged