Dynamic imports & lite panels
LiveTL/LiveTL pull request #343
Opened 2021-09-13 22:58 UTC by KentoNishi

Mainly for the Holodex integration.

2021-09-15 16:03 UTC, r2dev2 reviewed
Do we need these now that we're not doing the holodex embed?

2021-09-15 16:03 UTC, r2dev2 commented on src/components/MainPane.svelte
> +      ).default;
use `Promise.all`

2021-09-15 20:10 UTC, KentoNishi commented
Yea this is good regardless of dex, speeds up initial load and stuff

2021-09-16 05:08 UTC, r2dev2 approved these changes
Tw mk me re-con m li-fe ch-s.

2021-09-16 06:58 UTC, KentoNishi commented
I HAVEN'T CHANGED SHT YET LMAO

2021-09-16 06:59 UTC, KentoNishi commented
`Tw mk me re-con m li-fe ch-s.`

`[en] Tailwind making me reconsider my life choices.`

2021-09-19 08:22 UTC, ChrRubin requested changes
- Did you run the project thru a formatter outside of eslint? There's dangling commas everywhere that isn't allowed by the standardjs eslint rules.
- Tooltip doesn't offset properly in `lite.html`, but I think that's because of a change I made to the tooltip component a bit back. I'll see if I can make it work nicely.

2021-09-19 08:22 UTC, ChrRubin commented on src/components/Captions.svelte
> +    height: 100%;
This change does this:
![image](https://user-images.githubusercontent.com/20059164/133919912-605ec384-4076-479e-9536-59586a98658f.png)

2021-09-19 08:22 UTC, ChrRubin commented on src/components/IntroMessage.svelte
> +<div class="rounded bg-gray-900 px-2 py-1 m-1 flex flex-col gap-1 leading-none">
Not a fan of how cramped the text looks with this change.

2021-09-19 08:22 UTC, ChrRubin commented on src/components/LiteOptions.svelte
> +<div class="bg-dark-700" bind:this={div}>
Should add a padding

2021-09-19 08:22 UTC, ChrRubin commented on src/components/Watch.svelte
> +  }
Could've just used tailwind for these

2021-09-19 08:22 UTC, ChrRubin commented on src/components/settings/CommonFilterCards.svelte
> +<Card title="Filters" icon="cloud" noGap>
The `filter_alt` icon would be better for "Filters"

2021-10-03 19:18 UTC, KentoNishi commented
@ChrRubin i did the requested changes, lite.html is currently unused but im sure we'll find a use for it eventually so imma leave that in there without touching it up. as long as the main ui is good, i think we're ready to go

2021-10-04 04:58 UTC, ChrRubin approved these changes
Once this is merged I'll work on getting 6.8 merged into smelte, and then we'll finally be ready for beta

2021-10-04 05:02 UTC, r2dev2 commented on src/js/translator-mode.js
> -      replaced.push(replacement || text);
Is eslint sure about this one? Is it correct to not push `text` if `replacement` is an empty string?

2021-10-04 08:42 UTC, merged