Disable spam protection for gigachad users
LiveTL/LiveTL pull request #352
Opened 2021-10-18 23:52 UTC by r2dev2

- allow non-plebs past the spam protection
- user interface option for enabling taishi bonk
- increase default spam protection trigger to 7 msgs / 10 s

Requested by <@713592330552213554> in the discord

2021-10-19 06:26 UTC, KentoNishi approved these changes

2021-10-19 06:27 UTC, KentoNishi commented
preliminary approval before a final check by our lord and savior ~lightning mcqueen~ @ChrRubin

2021-10-19 06:59 UTC, ChrRubin requested changes
Please don't call me the lord and saviour, I think I'm more of a devil than anything lmao

2021-10-19 06:59 UTC, ChrRubin commented on src/components/SpamProtection.svelte
> +  />
This can be worded better, its not exactly clear what this setting does. 

Something along the lines of "Include authorized users in spam detection" would be better. The term "authorized users" is still vague, but it would at least get the point across that enabling this setting will enable spam detection even on users that are deemed "authorized".

2021-10-19 07:04 UTC, KentoNishi commented on src/components/SpamProtection.svelte
> +  />
What about "trusted translators"?

2021-10-19 07:05 UTC, ChrRubin commented on src/components/SpamProtection.svelte
> +  />
It includes channel moderators and owner, so its not limited to translators

2021-10-19 07:06 UTC, KentoNishi commented on src/components/SpamProtection.svelte
> +  />
This setting only applies to Mchad and LiveTL api no? I don't think moderators and owners matter for that 

Either way, I think "trusted" makes more sense than "authorized"

2021-10-19 07:09 UTC, ChrRubin commented on src/components/SpamProtection.svelte
> +  />
https://github.com/LiveTL/LiveTL/blob/57b80ce1ed7ad630cc53505ca9ac8fc6bcf09f80/src/js/constants.js#L69-L70

But yeah "trusted users" would at least be better than "authorized".

2021-10-19 18:02 UTC, r2dev2 commented on src/components/SpamProtection.svelte
> +  />
Ok so I changed it to "Trusted user spam protection." Is that clearer?

2021-10-19 18:11 UTC, ChrRubin commented on src/components/SpamProtection.svelte
> +  />
Not really. "Spam protection" suggests that the extension user is being protected from spam, which works fine as the overall name of the setting/feature.

"Trusted user spam protection" almost sounds like only certain trusted users would benefit from spam protection, which would be very confusing as a concept.

2021-10-19 18:13 UTC, ChrRubin commented on src/components/SpamProtection.svelte
> +  />
That or that the spam protection is being supplied by said trusted users, which isn't what's happening here

2021-10-19 22:43 UTC, r2dev2 commented on src/components/SpamProtection.svelte
> +  />
Should I say "Bonk trusted users" then?

2021-10-19 23:48 UTC, KentoNishi commented on src/components/SpamProtection.svelte
> +  />
Make the checkbox say "Bypass spam detection filter for trusted users" checked by default

2021-10-20 02:41 UTC, ChrRubin approved these changes

2021-10-20 15:01 UTC, merged