Validate regex
LiveTL/LiveTL pull request #367
Opened 2021-12-07 09:59 UTC by ChrRubin

Checks that the regex from custom filters are valid, and ignore the those that are invalid. Also includes UI changes to show user that the particular regex is invalid:

![image](https://user-images.githubusercontent.com/20059164/145007295-9e7053c8-147d-4773-b668-2a9a7097ac49.png)

Fixes #362.

2021-12-07 10:32 UTC, ChrRubin commented
I've also removed auto delete when rule is empty cause its just annoying UX.

2021-12-13 07:00 UTC, r2dev2 requested changes

2021-12-13 07:00 UTC, r2dev2 commented on src/js/filter.js
> +      ? validateRegex(filters.map(transform).filter(e => e).join('|'))
we should make it such that if one regex is wrong, it doesn't disable all the regexs by applying `validateRegex` logic to each regex that is joined

2021-12-18 19:39 UTC, r2dev2 commented on src/js/filter.js
> +      ? validateRegex(filters.map(transform).filter(e => e).join('|'))
I did it in 4836f01

2021-12-18 19:39 UTC, r2dev2 approved these changes

2021-12-20 04:29 UTC, ChrRubin commented
Yup those changes seems good (I can't approve my own PR)

2021-12-20 08:59 UTC, r2dev2 commented
@KentoNishi good for merge?

2021-12-20 09:12 UTC, KentoNishi approved these changes

2021-12-20 09:13 UTC, merged