Twitch support
LiveTL/LiveTL pull request #384
Opened 2022-01-18 07:38 UTC by ChrRubin

Adds Twitch support, including with Mchad.

## Features
- Uses MutationObserver for parsing message since tmi.js doesn't work for twitch VODs. My implementation works for both live streams and VODs.
- Popout Mode and Embed Mode. I've also added a hide button since not everyone wants to see the blue bar when they're just watching normal English streamers.
- Settings will pop out when using Embed Mode, for both Twitch and YT.
- Useless settings such as Captions and Chat Zoom are hidden when it is opened from Twitch.

## Known issues
- Verified/Mod/Broadcaster detection does not work on Twitch locales other than English, for the same reasons it used to not work on YT.
- Blocked users on Twitch share the same storage object and filter settings with YT, mainly cause I'm lazy and this just works lol.
- Embed Mode does not look good on light mode Twitch, but who uses light mode anyways.

## Screenshots
| Injected buttons | Embed Mode |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20059164/149890835-d5b395db-11bf-4eee-8608-af2962f4779e.png) | ![image](https://user-images.githubusercontent.com/20059164/149890895-c1555cf9-e954-4868-a39e-72d642cca165.png) |

![image](https://user-images.githubusercontent.com/20059164/149891079-19c3f016-d552-4bdd-ba2c-9b8885e7adb8.png)

![image](https://user-images.githubusercontent.com/20059164/149891320-b86d9e04-da82-45d6-81e4-965b86f703a7.png)

2022-01-18 07:48 UTC, ChrRubin commented
Oh I just realized on my screenshot that @ tags don't show up in the output, have to fix that

2022-01-20 07:36 UTC, KentoNishi commented
https://user-images.githubusercontent.com/38841491/150293898-ec702bd6-5b46-4e1c-976d-866bc5691ceb.mp4


@ChrRubin I made changes to the injection script to add resizable panes, can you take a look? Other than that I think it's good to go

2022-01-20 07:37 UTC, KentoNishi approved these changes

2022-01-20 12:47 UTC, ChrRubin commented on src/ts/content_scripts/twitch-injector.ts
> +    dots.style.transform = 'translate(-2px, -1.5px)';
Is this needed for something? The non-centerness is bugging me lmao

2022-01-20 12:50 UTC, ChrRubin commented on src/ts/content_scripts/twitch-injector.ts
> +      transform: translateY(-1px);
Same thing here. Unless my eyes are bad this makes it look off center

2022-01-20 22:50 UTC, r2dev2 requested changes
TLDR: Everything is more or less fine, but embed does not work on firefox (tried both production and dev) because `chrome.tabs` does not exist for some reason.

Can you make it so that the YouTube LiveTL launcher colors are also dark as the dark variant won in a landslide in the poll?

![poll: 1 - 15 for light - dark](https://user-images.githubusercontent.com/50760816/150431868-3f04e977-e6a6-4633-9e22-3661d338ac50.png)


Also, should we put some default filters against mod bots or not because when I open up hasanabi's chat, I get bot spam.

![bot spamming](https://user-images.githubusercontent.com/50760816/150432555-664d6636-daba-486a-88a1-43f7aecfa4ab.png)

2022-01-20 22:50 UTC, r2dev2 commented on src/ts/sources.ts
> +  const port = chrome.tabs.connect(
`chrome.tabs` doesn't seem to be available when launching embed mode which makes embed mode not work on firefox
![undefined chrome.tabs](https://user-images.githubusercontent.com/50760816/150433026-35ec1ce1-1d84-4a1d-98fc-e0c90e59a198.png)

2022-01-21 08:32 UTC, ChrRubin commented
> Can you make it so that the YouTube LiveTL launcher colors are also dark as the dark variant won in a landslide in the poll?

I'll do this in a separate PR, wanted to clean up some of that code anyway.

> Also, should we put some default filters against mod bots or not because when I open up hasanabi's chat, I get bot spam.

There's not really an easy way to do this, bots usually just show up as moderators. AFAIK not even the Twitch API can identify whether a user is a bot. I guess if we REALLY wanted to do this we'd have to keep a local copy of known bot names.

2022-01-21 14:10 UTC, ChrRubin commented
90c4389 adds an option to disable Twitch support globally, which will stop the LTL buttons from being injected, in case there's people who never want to use this.

![image](https://user-images.githubusercontent.com/20059164/150540984-1c99b802-e83d-4421-99c7-ca04b3381ae1.png)

2022-01-21 18:53 UTC, KentoNishi commented
@ChrRubin so typechecks are failing, idk why some of the port message objects are untyped? it doesn't even compile now
![image](https://user-images.githubusercontent.com/38841491/150583983-763bd1d8-52c4-4f10-bd0c-68d182746733.png)

2022-01-22 01:23 UTC, ChrRubin commented
> @ChrRubin so typechecks are failing, idk why some of the port message objects are untyped? it doesn't even compile now
> ![image](https://user-images.githubusercontent.com/38841491/150583983-763bd1d8-52c4-4f10-bd0c-68d182746733.png)
> 

@KentoNishi did you recurse pull? I updated the submod

2022-01-22 01:27 UTC, KentoNishi commented
OHHHHHH

2022-01-22 02:04 UTC, r2dev2 approved these changes

2022-01-22 02:15 UTC, merged